# Generated by Django 4.2.9 on 2024-02-04 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_watchlisters'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='listings_won', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
